{
	"version": 1616061038,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/artboard-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/alakypaadel-sheet0.png",
		"images/alakyball-sheet0.png",
		"images/alakyball-sheet1.png",
		"images/sprite10-sheet0.png",
		"images/makers-sheet0.png",
		"images/solideobj-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground.png",
		"images/padelgame-sheet0.png",
		"images/ballgame-sheet0.png",
		"images/ballgame-sheet1.png",
		"images/sprite11-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"images/tiledbackground2.png",
		"images/sprite18-sheet0.png",
		"images/sprite18-sheet1.png",
		"images/sprite14-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/tiledbackground4.png",
		"images/sprite21-sheet0.png",
		"images/sprite21-sheet1.png",
		"images/sprite22-sheet0.png",
		"images/tiledbackground6.png",
		"images/solidingame-sheet0.png",
		"images/solidingame-sheet1.png",
		"images/tiledbackground7.png",
		"images/sprite23-sheet0.png",
		"images/tiledbackground8.png",
		"images/tiledbackground9.png",
		"images/sprite24-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite28-sheet1.png",
		"media/click_003.ogg",
		"media/error_003.ogg",
		"media/mission_reef.ogg",
		"media/new_achievement.ogg",
		"media/buildtrees.ogg",
		"media/bol2.ogg",
		"media/bol.ogg",
		"media/ilove.ogg",
		"media/akisey dance.ogg",
		"media/chocolate addiction.ogg",
		"media/endless orgy.ogg",
		"media/dancing on the street nes.ogg",
		"media/happy.ogg",
		"media/flying me softly.ogg",
		"media/new eternal dance.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}